site_name: Dockerized Service Example
nav:
    - Home: index.md
    - Getting Started: getting-started.md
    - Architecture: architecture.md
    - API: api.md
    - Testing: testing.md
    - Changelog: changelog.md
    - About: about.md
theme:
  name: 'material'
  favicon: 'img/favicon.ico'
  logo: 'img/logo.png'
extra_css: ['stylesheets/extra.css']
repo_name: 'docker-service-example'
repo_url: 'https://github.com/brad-klocksiem-bfg/docker-service-example'